public without sharing class B2B_ConsultaClientesBasica_RP {
	public String ShippingStreet {get;set;}
	public String ShippingCity {get;set;}
	public String ShippingState {get;set;}
	public String ShippingPostalCode {get;set;}
	public String ShippingCountry {get;set;}
	public Boolean CUE_CAS_Activado {get;set;}
	public String Id {get;set;}
	public String Name {get;set;}
	public String CUE_TXT_Numero_Documento {get;set;}
	public String CUE_SEL_Gremios_Disp {get;set;}
	public String Email {get;set;}
	public String MobilePhone {get;set;}
	public String Phone {get;set;}
	public Boolean CUE_CAS_Dada_de_Baja {get;set;}
	public Boolean CON_CAS_Contacto_principal {get;set;}
	public String Code {get;set;}
	public String Message {get;set;}
}