/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Author:             everis
Company:        everis España
Description:    <Clase para Response en Envío de movimientos programados>

History:  <DESCRIPCIÓN DEL CAMBIO, REQUISITO, INCIDENCIA, CORRECTIVO O MEJORA QUE HIZO ACTUALIZAR/CREAR LA CLASE>

<27/11/2017>                      everis                       <Inicio de clase>
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
public without sharing class Batch_Envio_Mov_RP {
	public String errorCode{get;set;}
	public String errorMessage{get;set;}
}