/*
 * Clase que encapsula los datos a introducir en la request para la clase "Callout_Fac_MaestroClientes"
 *
 * @author EVERIS
 */
public without sharing class Callout_Fac_MaestroClientes_RQ {
	public String origenDeDatos {get;set;}
	public String accion {get; set;}
	public String nombreDelClienteProcedencia {get;set;}
	public String tipoCliente {get;set;}
	public String identificadorCompania {get;set;}
	public String identificadorUnicoCliente {get;set;}
	public String tipoDocumento {get;set;}
	public String tomadorNumeroDocumentoCliente {get;set;}
	public String numeroPoliza {get;set;}
	public String numeroClienteRelacionado {get;set;}
	public String nombreContacto {get;set;}
	public String mailContacto {get;set;}
	public String telefonoCuenta {get;set;}
	public String condicionPago {get;set;}
	public String metodoPago {get;set;}
	public String codigoEntidadBanco {get;set;}
	public String codigoSucursal {get;set;}
	public String digitosControl {get;set;}
	public String numeroCuenta {get;set;}
	public String numeroIBAN {get;set;}
	public String paisCuentaBancaria {get;set;}
	public String procedencia {get;set;}
	public String direccionRiesgoDomicilio {get;set;}
	public String direccionRiesgoCp {get;set;}
	public String direccionRiesgoProvincia {get;set;}
	public String paisCliente {get;set;}
	public String direccionRiesgoPoblacion {get;set;}
	public String RecordType {get;set;}
	public String idDireccion {get;set;}
	public String shippingStreet {get;set;}
	public String shippingCity {get;set;}
	public String shippingState {get;set;}
	public String shippingPostalCode {get;set;}
	public String shippingCountry {get;set;}
	public String idDirecPadre {get;set;}
	public String shippingStreetPadre {get;set;}
	public String shippingCityPadre {get;set;}
	public String shippingStatePadre {get;set;}
	public String shippingPostalCodePadre {get;set;}
	public String shippingCountryPadre {get;set;} 
	public String RecordTypePadre {get;set;}   
	/* public Callout_Fac_MaestroClientes_RQ(String origenDeDatos, String accion, String nombreDelClienteProcedencia, String tipoCliente, String identificadorCompania, String identificadorUnicoCliente, 
	String tipoDocumento, String tomadorNumeroDocumentoCliente, String numeroPoliza, String numeroClienteRelacionado, String nombreContacto, String mailContacto, String direccion, String telefonoCuenta, 
	String direccionRiesgoDomicilio, String direccionRiesgoCp, String direccionRiesgoProvincia, String paisCliente, String condicionPago, String metodoPago, Integer codigoEntidadBanco, 
	Integer codigoSucursal, Integer digitosControl, Integer numeroCuenta, String numeroIBAN, String paisCuentaBancaria){
		this.origenDeDatos = origenDeDatos;
		this.accion = accion;
		this.nombreDelClienteProcedencia = nombreDelClienteProcedencia;
		this.tipoCliente = tipoCliente;
		this.identificadorCompania = identificadorCompania;
		this.identificadorUnicoCliente = identificadorUnicoCliente;
		this.tipoDocumento = tipoDocumento;
		this.tomadorNumeroDocumentoCliente = tomadorNumeroDocumentoCliente;
		this.numeroPoliza = numeroPoliza;
		this.numeroClienteRelacionado = numeroClienteRelacionado;
		this.nombreContacto = nombreContacto;
		this.mailContacto = mailContacto;
		this.direccion = direccion;
		this.telefonoCuenta = telefonoCuenta;
		this.direccionRiesgoDomicilio = direccionRiesgoDomicilio;
		this.direccionRiesgoCp = direccionRiesgoCp;
		this.direccionRiesgoProvincia = direccionRiesgoProvincia;
		this.paisCliente = paisCliente;
		this.condicionPago = condicionPago;
		this.metodoPago = metodoPago;
		this.codigoEntidadBanco = codigoEntidadBanco;
		this.codigoSucursal = codigoSucursal;
		this.digitosControl = digitosControl;
		this.numeroCuenta = numeroCuenta;
		this.numeroIBAN = numeroIBAN;
		this.paisCuentaBancaria = paisCuentaBancaria;
	}*/


}