/**
 * Clase con las variables globales.
 * 
 * @author EVERIS
 * 
 */
public without sharing class Util_variablesGlobales
{
	public static boolean vuelveSondeo = false;
	public static String estadoVueltaSondeo;
	public static String faseVueltaSondeo;
	public static boolean borradoContactoMixto = false;
	public static boolean contactoPrincipal = true;
	public static List<Task> listaTareasGeneradas = new List<Task>();
	public static boolean noCrearClonOT = false;
	public static List<Case> listaCasosActualizar = new List<Case>();

	/*
	 *
	 *   CONSTANTES DE SINIESTRO
	 *   SINI_NOMBRE_VARIABLE;
	 *
	 */




	/*
	 *
	 *   CONSTANTES DE COMPAÑÍA
	 *   CIA_NOMBRE_VARIABLE;
	 *
	 */
	/*
    public static String CIA_IDENTIF_SEGURCAIXA = '';
    public static String CIA_IDENTIF_RGA = '';
    public static String CIA_IDENTIF_ALMUDENA = '';
    public static String CIA_IDENTIF_SANTANDER = '';
	 */

}//FIN Util_variablesGlobales