Id,Name,CUE_TXT_Identificador__c,CUE_EMA_Email__c,RecordTypeId,CUE_TXT_Numero_Documento__c,CUE_TXT_PrimerApellido__c,CUE_TXT_Nombre__c,CUE_CAS_No_Permite_Servicio_B2C__c,CUE_TXT_Presentacion__c,CUE_TXT_SegundoApellido__c,CUE_DIV_Limite_Graves__c,CUE_SEL_GestionIndemnizable__c,CUE_DIV_Limite_Actuacion__c,Type,ShippingPostalCode,ShippingStreet,CUE_LKP_Cuenta_principal__c,CUE_CAS_Activado__c,ShippingCity,ShippingState,CUE_CAS_Robinson__c
1019E00000P9vBIQAZ,SegurCaixa,1018,companiaSCExample@gmail.es,0129E0000004pci,12458764F,Martinez,Alex,false,#USUARIO# Bienvenido #SALUDO#,Sanchez,2000.00,Registra Documentación Indemnizable,1000.00,,,,,
2019E00000P9vBIQAZ,Manolo,2018,manoloExample@gmail.es,0129E0000004pcJQAQ,02458764F,Diaz,Manolo,false,#USUARIO# Bienvenido2 #SALUDO#,Gutierrez,,,,,,,,
0019E00000XZI54QAH,SeVeVi,12453267Y,seveviExample@gmail.es,0129E0000004pcJQAQ,12453267Y,Vega,Seila,false,,,0.0,,,,,,,
6019E00000P9vBIQAZ,SegurCaixa2,1118,B2BPrincipalExample@gmail.es,0129E0000004pcT,12451764F,Martinez,Alex,false,#USUARIO# Bienvenido #SALUDO#,Sanchez,2000.00,,,Empresa,28051,Avenida de Europa 34,,
0019E00000UHDO5QAP,Holiday Gym,555001,holidaygymhs@gmail.com,0129E0000004pcTQAQ,,,,false,,,,,,Direccion,,,,,
3329E00000UHDO5QAP,Holiday Gym2,1255,holidaygymhs2@gmail.com,0129E0000004pcTQAQ,,,,false,,,,,,Direccion,28050,Avenida de Europa 34,,,Madrid,Madrid,
