Id,Name,AYU_TXT_Descripcion__c,AYU_SEL_Tipo__c,AYU_TXT_Identificador__c
a119E000000VKIr,AY-0008,Grupo de causa,Ayuda árbol: Grupo de causa,AY-0008
a119E000000X88f,AYU-00000000,Indemnizable,Ayuda árbol: Indemnizable,AY-0009
a120E000000VKIr,AY-00010,Tipo de averia,Ayuda árbol: Tipo de avería,AY-00010
a121E000000VKIr,AY-00011,Detalle de la avería,Ayuda árbol: Detalle de la avería,AY-00011
a122E000000VKIr,AY-00012,Daños a Perjudicados,Ayuda árbol: Daños a Perjudicados,AY-00012
