Id,Name,EstimatedDuration,DurationType,TDT_SEL_Categoria__c,TDT_SEL_Gremio__c,ShouldAutoCreateSvcAppt,TDT_TXT_Identificador__c,ShouldAutoCreateSvcAppt
10q9E0000009P12,Tipo de Trabajo por Defecto,2.00,Hours,02,21,false,6666,true
08q9E0000008Xzv,Reparacion aire acondicionado,2.00,Hours,01,21,true,5555,true
08q9E0000009P0h,Filtraciones a través del tejado,30,Hours,01,27,true,2702,true
08q9E0000008XYZ,Reparacion aire acondicionado,2.00,Hours,01,21,true,5500,true
08q9E0000009P34,Filtraciones a través del tejado,30,Hours,01,27,true,2722,true
08q9E0000008X11,Reparacion aire acondicionado,2.00,Hours,01,21,true,5544,true
08q9E0000009P16,Filtraciones a través del tejado,30,Hours,01,27,true,2733,true
a169E000000R4MsQAK,Filtraciones a través del tejado,30,Hours,01,27,true,2734,true
08q9E0000009P12,Reparacion aire acondicionado,2.00,Hours,02,21,true,5533,true